language: scala
sudo: false
matrix:
  include:
  - scala: 2.11.12
    jdk: openjdk7
  - scala: 2.12.4
    jdk: oraclejdk8
  - scala: 2.13.0-M2
    jdk: oraclejdk8
  - jdk: oraclejdk8
    sudo: required
    dist: trusty
    before_install:
    - curl https://raw.githubusercontent.com/scala-native/scala-native/0f69c875d2cb2/bin/travis_setup.sh | bash -x
    script:
    - sbt protobufRuntimeScalaNative/compile "show protobufRuntimeScalaNative/nativeMissingDependencies"
